In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten

Using TensorFlow backend.


In [2]:
model=Sequential()

In [3]:
model.add(Convolution2D(32,(3,3),input_shape=(128,128,3),activation="relu"))

In [4]:
model.add(MaxPooling2D(pool_size = (2, 2)))

In [5]:
model.add(Flatten())

In [6]:
model.add(Dense(init="uniform",activation="relu",output_dim=120))

C:\Users\Saif\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=120, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [7]:
model.add(Dense(init="uniform",activation="relu",output_dim=100))

C:\Users\Saif\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=100, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [8]:
model.add(Dense(init="uniform",activation="sigmoid",output_dim=3))

C:\Users\Saif\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=3, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [9]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [10]:
from keras.preprocessing.image import ImageDataGenerator

In [11]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

In [12]:
test_datagen = ImageDataGenerator(rescale = 1./255)

In [13]:
x_train = train_datagen.flow_from_directory(r'C:\Users\Saif\face recognition\training_set',
                                                 target_size = (128, 128),
                                                 batch_size = 32,
                                                     class_mode = 'categorical')

Found 1790 images belonging to 3 classes.


In [14]:
x_test = test_datagen.flow_from_directory(r'C:\Users\Saif\face recognition\testing_set',
                                            target_size = (128, 128),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 416 images belonging to 3 classes.


In [15]:
print(x_train.class_indices)

{'hrithik roshan': 0, 'shahrukh khan': 1, 'tiger shroff': 2}


In [16]:
x_train[0]

(array([[[[0.        , 0.00392157, 0.        ],
          [0.        , 0.00392157, 0.        ],
          [0.        , 0.00392157, 0.        ],
          ...,
          [0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        ]],
 
         [[0.        , 0.00392157, 0.        ],
          [0.        , 0.00392157, 0.        ],
          [0.        , 0.00392157, 0.        ],
          ...,
          [0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        ]],
 
         [[0.        , 0.00392157, 0.        ],
          [0.        , 0.00392157, 0.        ],
          [0.        , 0.00392157, 0.        ],
          ...,
          [0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        ],
          [0.        , 0.        , 0.        ]],
 
         ...,
 
         [[0.        , 0.        , 0.        ],
          [0.     

In [18]:
model.fit_generator(x_train,
                         steps_per_epoch = 56,
                         epochs = 20,
                         validation_data = x_test,
                         validation_steps = 13)

Epoch 1/20
56/56 [==============================] - 60s 1s/step - loss: 1.0861 - accuracy: 0.3810 - val_loss: 1.0355 - val_accuracy: 0.3197
Epoch 2/20
56/56 [==============================] - 33s 588ms/step - loss: 1.0190 - accuracy: 0.4682 - val_loss: 1.0178 - val_accuracy: 0.3630
Epoch 3/20
56/56 [==============================] - 34s 603ms/step - loss: 0.9412 - accuracy: 0.5542 - val_loss: 0.6899 - val_accuracy: 0.7236
Epoch 4/20
56/56 [==============================] - 34s 608ms/step - loss: 0.8484 - accuracy: 0.6257 - val_loss: 0.7638 - val_accuracy: 0.7139
Epoch 5/20
56/56 [==============================] - 35s 618ms/step - loss: 0.7515 - accuracy: 0.6838 - val_loss: 1.0000 - val_accuracy: 0.6659
Epoch 6/20
56/56 [==============================] - 34s 614ms/step - loss: 0.6776 - accuracy: 0.7246 - val_loss: 0.3380 - val_accuracy: 0.8750
Epoch 7/20
56/56 [==============================] - 35s 628ms/step - loss: 0.5869 - accuracy: 0.7581 - val_loss: 0.2339 - val_accuracy: 0.9159
Ep

In [19]:
model.save("face recognition128.h5")

In [20]:
from keras.models import load_model

In [21]:
import cv2

In [22]:
import numpy as np

In [23]:
model2=load_model("face recognition128.h5")

In [24]:
model2.compile(loss='categorical_crossentropy',
                      optimizer='adam',
                      metrics=['accuracy'])

In [25]:
from skimage.transform import resize

In [26]:
def detect(frame):
    try:
        img = resize(frame,(128,128))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)
        pred=model.predict_classes(img)
        print(pred)
        print(prediction)
        return prediction
    except AttributeError:
        print("shape not found")

In [39]:
frame=cv2.imread(r"C:\Users\Saif\face recognition\testing_set\tiger shroff\2Q__ (47).jpg")

In [40]:
data=detect(frame)

[2]
[[2.9166127e-05 2.1349592e-03 1.4592700e-01]]


In [41]:
data

array([[2.9166127e-05, 2.1349592e-03, 1.4592700e-01]], dtype=float32)

In [42]:
data1=list(data[0])

In [43]:
a=max(data[0])

In [44]:
a

0.145927

In [45]:
type(data1)

list

In [46]:
data1.index(a)

2